/**
 * The hosted front door.
 *
 * No account, no setup, no data left behind: explain the workflow, state the
 * privacy position up front, and let someone analyse a report they already
 * have without installing anything.
 */
import api from '../api.js';
import { esc, toast } from '../ui.js';
import { icons } from '../icons.js';
import { EVALUATION_AREAS, GRADE_CONFIG, CHECKLIST } from '/shared/xr-metrics/index.js';
import { UNITY_ASSET_STORE_URL, unityCta } from '../brand.js';
import { lensHTML, initLens } from '../lens.js';

/**
 * One shared markup builder so Home and Help cannot drift apart.
 * `blurb` is optional: Help states the same offer in its own words.
 */
function unityCtaHTML(headline, blurb) {
  const cta = unityCta();
  return `
    <div class="unity-cta">
      <div class="uc-text">
        <div class="uc-head">${esc(headline)}</div>
        <p>${esc(blurb ?? cta.blurb)}</p>
      </div>
      <a class="btn primary uc-btn" href="${UNITY_ASSET_STORE_URL}"
         target="_blank" rel="noopener noreferrer">
        ${esc(cta.label)} <span aria-hidden="true">→</span>
        <span class="sr-only">(opens in a new tab)</span>
      </a>
    </div>`;
}

/**
 * The two ways into a test. Running from Unity is the product; importing a
 * JSON by hand is the fallback for a test you already ran, so it is stated
 * second and more quietly.
 */
const TEST_PATHS = [
  {
    n: '01',
    kind: 'primary',
    title: 'Run directly from Unity',
    body: 'Install the ImmersiTest Unity Package from the Unity Asset Store, run your XR '
        + 'application, and start a test from the ImmersiTest menu. When you stop Play Mode, '
        + 'your report is generated, uploaded, analysed and opened here automatically.',
    steps: ['Install', 'Test', 'Stop', 'Automatic analysis'],
  },
  {
    n: '02',
    kind: 'secondary',
    title: 'Already have a test report?',
    body: 'Import the JSON generated by ImmersiTest. You will find it in your Unity project’s '
        + 'XRTestReports folder. Add more than one to compare runs.',
    steps: ['XRTestReports', 'JSON', 'Upload', 'Analysis'],
  },
];

const HELP_STEPS = [
  ['01', 'Install ImmersiTest',
   'Install the ImmersiTest Unity Package from the Unity Asset Store, then add the profiler to your Unity scene.'],
  ['02', 'Run your XR application',
   'Run the application normally and complete the experience. Stopping Play Mode captures, uploads and opens the report for you.'],
  ['03', 'Complete XR Validation',
   'After the performance capture, manually assess the eight XR validation items.'],
  ['04', 'Review the analysis',
   'Review the Quality Score, XR Health, Fix First and XR Doctor findings.'],
  ['05', 'Download your report',
   'Download the professional PDF test report.'],
];



let disposeLens = () => {};

export async function renderLanding(main, { mode, ttlMinutes }) {
  disposeLens();
  main.innerHTML = `
    <section class="hero cinematic" aria-labelledby="hero-h">
      <div class="hero-inner">
        <div class="hero-copy">
          <div class="eyebrow tech">
            <span class="eb-tick" aria-hidden="true"></span>XR Application Diagnostics
          </div>
          <h1 id="hero-h">ImmersiTest</h1>
          <p class="tagline">
            <span>Test the Experience.</span>
            <span>Trust the Immersion.</span>
          </p>
          <p class="lede signature">
            Measure what your profiler can see.<br>
            <b>Validate what only humans can experience.</b>
          </p>
          <div class="hero-actions">
            <a class="btn primary lg" href="#/analyze">Start New Test <span aria-hidden="true">→</span></a>
            <a class="btn ghost lg" href="#/docs">How It Works</a>
          </div>
          <div class="pipeline" aria-hidden="true">
            <span class="on"><i></i>Focus</span><span class="sep">/</span>
            <span class="on"><i></i>Inspect</span><span class="sep">/</span>
            <span class="on"><i></i>Diagnose</span>
          </div>
        </div>
        <div class="hero-visual">${lensHTML()}</div>
      </div>
    </section>

    <section class="section" aria-labelledby="unity-h">
      <h3 id="unity-h">Using Unity?</h3>
      ${unityCtaHTML('Install ImmersiTest from the Unity Asset Store')}
    </section>

    <section class="section" aria-labelledby="flow-h">
      <h3 id="flow-h">How it works <span class="hint">install once, then it is two clicks</span></h3>
      <ol class="flow">
        ${HELP_STEPS.map(
          ([n, title]) => `<li class="flow-step">
            <span class="fs-n" aria-hidden="true">${n}</span>
            <span class="fs-t">${esc(title)}</span>
          </li>`,
        ).join('')}
      </ol>
    </section>

    <section class="section privacy-panel" aria-labelledby="priv-h">
      <h3 id="priv-h">What is uploaded <span class="hint">and what never is</span></h3>
      <div class="priv-cols">
        <div class="priv-col yes">
          <div class="pc-head"><span class="pc-dot" aria-hidden="true"></span>Uploaded</div>
          <ul>
            <li>The generated XR Test Profiler JSON — frame timings, memory figures,
              device/GPU/OS strings and the sample series.</li>
          </ul>
        </div>
        <div class="priv-col no">
          <div class="pc-head"><span class="pc-dot" aria-hidden="true"></span>Never uploaded</div>
          <ul>
            <li>Your Unity project or project folder</li>
            <li>C# source, scenes, prefabs</li>
            <li>Assets, models, textures, materials</li>
            <li>Your repository or any version-control metadata</li>
          </ul>
        </div>
      </div>
      <p class="muted" style="font-size:13px;margin-top:14px">
        Reports are held in memory only and deleted automatically after
        <b>${esc(String(ttlMinutes))} minutes</b>. There are no accounts, so nothing is tied to an
        identity, and you can delete an analysis yourself at any time.
        ${mode === 'local' ? '<b>This instance is running in local development mode.</b>' : ''}
      </p>
    </section>`;

  disposeLens = initLens(main);
}

/* --------------------------------------------------------- analyse page -- */

export function renderAnalyze(main) {
  main.innerHTML = `
    <div class="page-head">
      <div>
        <div class="eyebrow tech"><span class="eb-tick" aria-hidden="true"></span>New Test</div>
        <h1>Start a New Test</h1>
        <div class="meta"><span class="muted">ImmersiTest runs your test from inside Unity and opens
          the report for you. You can also import a report you already captured.</span></div>
      </div>
    </div>

    <section class="section paths-section" aria-labelledby="paths-h">
      <h3 id="paths-h" class="sr-only">Two ways to run a test</h3>
      <ol class="paths">
        ${TEST_PATHS.map(
          (p) => `<li class="path ${p.kind}">
            <span class="p-n" aria-hidden="true">${p.n}</span>
            <div class="p-body">
              <h4 class="p-title">${esc(p.title)}</h4>
              <p class="p-text">${esc(p.body)}</p>
              <ol class="p-steps" aria-label="${esc(p.title)} sequence">
                ${p.steps.map((s) => `<li>${esc(s)}</li>`).join('')}
              </ol>
            </div>
          </li>`,
        ).join('<li class="path-or" aria-hidden="true"><span>or</span></li>')}
      </ol>
    </section>

    <section class="section">
      <div class="dropzone" id="drop">
        <div class="dz-icon" aria-hidden="true">${icons.upload(38)}</div>
        <p><b>Drag and drop XR test reports here</b></p>
        <p class="muted" style="font-size:13px;margin:6px 0 12px">or</p>
        <button type="button" class="btn primary" id="pick">Choose Files</button>
        <label for="fileInput" class="sr-only">Choose profiler JSON files</label>
        <input type="file" id="fileInput" accept=".json,application/json" multiple hidden>
        <p class="muted" style="font-size:12.5px;margin-top:14px">
          Only the profiler JSON is sent. Your analysis is temporary and is deleted automatically.
        </p>
      </div>
      <div id="status" aria-live="polite"></div>
    </section>`;

  const input = main.querySelector('#fileInput');
  const drop = main.querySelector('#drop');
  const status = main.querySelector('#status');

  async function send(files) {
    const list = [...files].filter((f) => f.name.toLowerCase().endsWith('.json'));
    if (!list.length) {
      toast('Only .json profiler reports can be analysed.', 'error');
      return;
    }

    status.innerHTML = `<p class="muted" style="font-size:13px;margin-top:12px">Uploading ${list.length} report(s)…</p>`;

    let token = null;
    const failures = [];
    for (const file of list) {
      let doc;
      try {
        doc = JSON.parse(await file.text());
      } catch {
        failures.push(`${file.name}: not valid JSON.`);
        continue;
      }
      try {
        if (!token) {
          token = (await api.analyze(doc, file.name)).token;
        } else {
          await api.addAnalysisReport(token, doc, file.name);
        }
      } catch (err) {
        failures.push(`${file.name}: ${err.userMessage ?? err.message}`);
      }
    }

    if (failures.length) {
      status.innerHTML = `<ul class="reco" style="margin-top:12px">${failures
        .map((f) => `<li class="reco-critical"><span>${esc(f)}</span></li>`)
        .join('')}</ul>`;
    }
    if (token) {
      toast('Analysis ready', 'success');
      location.hash = `#/r/${token}`;
    } else if (!failures.length) {
      status.innerHTML = '<p class="field-error show">Nothing could be analysed.</p>';
    }
  }

  main.querySelector('#pick').addEventListener('click', () => input.click());
  input.addEventListener('change', () => {
    send(input.files);
    input.value = '';
  });
  ['dragenter', 'dragover'].forEach((ev) =>
    drop.addEventListener(ev, (e) => {
      e.preventDefault();
      drop.classList.add('over');
    }),
  );
  ['dragleave', 'drop'].forEach((ev) =>
    drop.addEventListener(ev, (e) => {
      e.preventDefault();
      drop.classList.remove('over');
    }),
  );
  drop.addEventListener('drop', (e) => send(e.dataTransfer?.files ?? []));
}

/* ------------------------------------------------------------ docs page -- */

export function renderDocs(main, { ttlMinutes }) {
  main.innerHTML = `
    <div class="page-head">
      <div>
        <div class="eyebrow">Help</div>
        <h1>How It Works</h1>
      </div>
      <div class="actions"><a class="btn primary" href="#/analyze">Start New Test</a></div>
    </div>

    <section class="section" aria-labelledby="steps-h">
      <h3 id="steps-h">How It Works
        <span class="hint">a five-stage XR testing pipeline</span></h3>
      <ol class="pipeline-stages">
        ${HELP_STEPS.map(
          ([n, title, body], i) => `<li class="pstage">
            <span class="ps-rail" aria-hidden="true">
              <span class="ps-node"></span>
              ${i < HELP_STEPS.length - 1 ? '<span class="ps-line"></span>' : ''}
            </span>
            <span class="ps-body">
              <span class="ps-n">${n}</span>
              <span class="ps-t">${esc(title)}</span>
              <span class="ps-d">${esc(body)}</span>
            </span>
          </li>`,
        ).join('')}
      </ol>
    </section>

    <section class="section cta-section" aria-labelledby="pkg-h">
      <h3 id="pkg-h" class="sr-only">Get the Unity package</h3>
      ${unityCtaHTML(
        'Install ImmersiTest from the Unity Asset Store',
        'Install the ImmersiTest Unity Package from the Unity Asset Store, add it to your Unity '
        + 'project, and run your XR application normally. ImmersiTest handles the capture and '
        + 'analysis workflow automatically when you stop Play Mode.',
      )}
      <p class="cta-alt">
        <b>Already completed a test?</b>
        If you already have an ImmersiTest JSON report, import it from your Unity project’s
        <code>XRTestReports</code> folder using <a href="#/analyze">New Test</a>.
      </p>
    </section>

    <section class="section" aria-labelledby="checks-h">
      <h3 id="checks-h">What ImmersiTest Checks
        <span class="hint">${GRADE_CONFIG.maxPerformance} performance + ${GRADE_CONFIG.maxChecklist} XR validation = 100</span></h3>
      <div class="area-grid">
        ${EVALUATION_AREAS.filter((a) => a.id !== 'validation').map(
          (a) => `<div class="area static">
            <div class="a-top"><span class="a-label">${esc(a.label)}</span></div>
            <div class="a-blurb">${esc(a.blurb)}</div>
          </div>`,
        ).join('')}
      </div>
      <p class="muted" style="font-size:13px;margin-top:14px">
        Four measured metrics — Average FPS, Bad Frame %, Average Frame Time and Memory —
        carry 15 marks each. ${CHECKLIST.length} XR validation items carry 5 marks each.
        Minimum FPS, 1% Low FPS, draw calls, triangles and battery are captured and reported
        as diagnostics but never scored.
      </p>
    </section>

    <section class="section" aria-labelledby="val-h">
      <h3 id="val-h">XR Validation Items <span class="hint">you assess these; a profiler cannot</span></h3>
      ${CHECKLIST.map(
        (c) => `<div class="check-row static">
          <div class="check-idx" aria-hidden="true">${esc(c.n)}</div>
          <div class="ctext">${esc(c.t)}<small>${esc(c.d)}</small></div>
        </div>`,
      ).join('')}
    </section>

    <section class="section vendor-panel" aria-labelledby="vendor-h">
      <h3 id="vendor-h">Wizardlenz XR Studio</h3>
      <div class="vendor-lockup">
        <img class="vendor-logo lg" src="assets/wizardlenz-logo.png"
             width="620" height="159" decoding="async" alt="Wizardlenz XR Studio">
        <div class="vendor-copy">
          <p>
            ImmersiTest is a free XR application testing tool by Wizardlenz XR Studio,
            created to help developers evaluate immersive applications before release.
          </p>
          <p class="vendor-motto">
            <b>Wizardlenz XR Studio</b>
            <span>“See the Magic. Be the Magic.”</span>
          </p>
        </div>
      </div>
    </section>

    <section class="section" aria-labelledby="priv-h">
      <h3 id="priv-h">Privacy</h3>
      <ul class="reco">
        <li class="reco-info"><b>Only the profiler JSON leaves your machine.</b>
          <span>No project files, C# source, scenes, prefabs, assets, models, textures, materials or repository data are uploaded.</span></li>
        <li class="reco-info"><b>No accounts.</b>
          <span>There is no login, signup or user profile. Nothing is tied to an identity.</span></li>
        <li class="reco-info"><b>Temporary by default.</b>
          <span>An analysis lives in memory for ${esc(String(ttlMinutes))} minutes and is then deleted. Download the PDF to keep it.</span></li>
        <li class="reco-info"><b>Delete on demand.</b>
          <span>Every report page can remove its analysis from the server immediately.</span></li>
      </ul>
    </section>`;
}
